app = "backend-white-snowflake-2031"
primary_region = "cdg"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[processes]]
  app = "uvicorn main_auth:app --host 0.0.0.0 --port 8080"
